### ISSUE TITLE
Consider implementing our own Json serializer

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/near-sdk-rs#24]
There are several issues with the serde_json:
* We had to fork it to make sure it does not produce float instructions, see: https://github.com/serde-rs/json/issues/567 and https://github.com/nearprotocol/json
* When trying to serialize an object not supported by json (e.g. a HashMap with has keys that are not primitive types) we are getting a runtime error instead of a compile-time error, because of serde framework restrictions. This leads to a lot of confusion and bad DevX as reported by users;
* In addition to a large code foot print of serde_json it needs serde itself which is also a large piece of code. It would be nice if contract developers could use a small and simple library that they could trust because they could easily read through.
* Serde_json has performance optimizations that might not make sense on Wasm.

**Comment by nearmax** [comment]
Unfortunately implementing Json serializer is a lot of work. Here is another json library but it does not uses derive macroses: https://github.com/maciejhirsz/json-rust

**Comment by fckt** [comment]
> When trying to serialize an object not supported by json (e.g. a HashMap with has keys that are not primitive types) we are getting a runtime error instead of a compile-time error, because of serde framework restrictions. This leads to a lot of confusion and bad DevX as reported by users;

I think, support of keys with custom types could lead to even more confusion as we taking interop with AssemblyScript contracts as a goal. It wouldn't be hard to check it with `near_bindgen` isn't it?

**Comment by nearmax** [comment]
Yes, that’s why we need compile time check. It is actually not possible to
check with near-bindgen because it works on AST so a function can be
returning some type and there is no way to see whether this type has
unsupported types somewhere deep in the type structure.

**Comment by evgenykuzyakov** [comment]
obsolete

**Comment by webmaster128** [comment]
@evgenykuzyakov @nearmax I'd be curious to learn with which solution or workaround you ended up with. Could you leave a little hint here? Thanks a lot!

**Comment by nearmax** [comment]
Explained in https://t.me/wasmblockchain

> At Near decided not to fork serde-json , because there are many other libraries that we would have to fork too which would degrade the DevX. Instead we canonicalize float NaNs.
